project:
    type: website
    output-dir: _docs
    render:
        - "*.ipynb"
        - "sbom/*.ipynb"
lang: es
format:
    html:
        theme: cosmo
        css: styles.css
        toc: true
        keep-md: true
    commonmark: default

website:
    twitter-card: true
    open-graph: true
    repo-actions: [issue]
    navbar:
        background: transparent
        search: true
    sidebar:
        style: floating
        pinned: true

metadata-files: [nbdev.yml, sidebar.yml]

execute:
    eval: false
    cache: false
